import { useMemo } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { Alert, Button, Input } from '../../components/ui/primitives'
import { EmptyState, ErrorState, LoadingPage, PermissionDenied, StatusBadge } from '../../components/common/states'
import { useSession } from '../../app/providers/use-session'
import { runtimeConfig } from '../../services/api/runtime-config'
import { useExams } from '../exams/exam-hooks'
import { examRoutes } from '../exams/exam-routes'
import { examStatusMeta } from '../exams/exam-types'
import { useLecturerSubject, useLecturerSubjects } from './subject-hooks'
import type { LecturerSubject } from './subject-types'
import './lecturer-subjects.css'

const isUuid = (value: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
const canOpenFeature = (id: string) => runtimeConfig.dataSource === 'mock' || isUuid(id)
const courseLabel = (subject: LecturerSubject) => `${subject.code} · ${subject.name}`
function Metric({ label, value }: { label: string; value: number | null }) { return <div className="metric-card"><span>{label}</span><strong>{value ?? '—'}</strong></div> }
function SubjectCard({ subject }: { subject: LecturerSubject }) { return <article className="subject-card"><div className="subject-actions"><small>{subject.code}</small></div><h2><Link to={`/lecturer/subjects/${subject.id}`}>{subject.name}</Link></h2><p className="muted">{subject.department}</p><StatusBadge label={subject.status === 'ACTIVE' ? 'Đang phụ trách' : 'Đã lưu trữ'} tone={subject.status === 'ACTIVE' ? 'success' : 'neutral'} /><dl className="subject-meta"><div><dt>Câu hỏi</dt><dd>{subject.questionCount ?? '—'}</dd></div><div><dt>Rubric</dt><dd>{subject.rubricCount ?? '—'}</dd></div><div><dt>Kỳ thi</dt><dd>{subject.examCount ?? '—'}</dd></div></dl><Link className="button outline" to={`/lecturer/subjects/${subject.id}`}>Xem môn học</Link></article> }

export function LecturerDashboardPage() {
  const { session } = useSession(); const subjects = useLecturerSubjects(); const exams = useExams({ page: 1, pageSize: 5, q: '', subject: '', status: '' })
  if (session.user && !session.user.roles.includes('lecturer')) return <PermissionDenied />
  if (subjects.isLoading || exams.isLoading) return <LoadingPage label="Đang tải không gian giảng viên" />
  if (subjects.isError || exams.isError) return <section className="state"><Alert tone="danger">Không thể tải dữ liệu tổng quan giảng viên.</Alert><Button onClick={() => { void subjects.refetch(); void exams.refetch() }}>Thử lại</Button></section>
  const rows = subjects.data ?? []; const examRows = exams.data?.items ?? []; const name = session.user?.displayName ?? 'Giảng viên'; const draftQuestions = rows.reduce((total, row) => total + (row.draftQuestionCount ?? 0), 0)
  return <main className="lecturer-page"><header className="lecturer-header"><div><p className="lecturer-eyebrow">AIVES · LECTURER WORKSPACE</p><h1>Xin chào, {name}</h1><p>Điều phối học phần, ngân hàng câu hỏi và các kỳ thi vấn đáp trong một không gian thống nhất.</p></div><div className="lecturer-actions"><Link className="button primary" to="/lecturer/subjects">Xem môn học</Link><Link className="button outline" to="/lecturer/rubrics">Quản lý Rubric</Link><Link className="button outline" to={examRoutes.new}>Tạo kỳ thi</Link></div></header><section className="metric-grid" aria-label="Tổng quan"><Metric label="Môn học phụ trách" value={rows.length} /><Metric label="Tổng số câu hỏi" value={rows.reduce((total, row) => total + (row.questionCount ?? 0), 0)} /><Metric label="Câu hỏi bản nháp" value={draftQuestions} /><Metric label="Kỳ thi sắp tới" value={examRows.filter((exam) => exam.status === 'DRAFT' || exam.status === 'SCHEDULED').length} /></section><div className="dashboard-grid"><section className="dashboard-section"><div className="subject-actions"><div><h2>Môn học phụ trách</h2><p className="muted">Các học phần bạn đang quản lý.</p></div><Link className="button outline" to="/lecturer/subjects">Xem tất cả môn học</Link></div><div className="subject-grid">{rows.slice(0, 4).map((subject) => <SubjectCard key={subject.id} subject={subject} />)}</div></section><section className="dashboard-section"><div className="subject-actions"><h2>Kỳ thi gần đây</h2><Link className="button outline" to={examRoutes.list}>Xem tất cả</Link></div>{!examRows.length ? <EmptyState title="Chưa có kỳ thi" description="Tạo kỳ thi đầu tiên từ màn hình Kỳ thi." /> : <ul className="link-list">{examRows.slice(0, 4).map((exam) => <li key={exam.id}><Link to={examRoutes.detail(exam.id)}>{exam.title}</Link><small className="muted">{exam.subjectName} · {examStatusMeta[exam.status].label}</small></li>)}</ul>}</section></div><section className="dashboard-section"><h2>Cần xử lý</h2><div className="subject-actions"><Link className="button outline" to="/lecturer/subjects">Rà soát {draftQuestions} câu hỏi bản nháp</Link><Link className="button outline" to={examRoutes.list}>Kiểm tra trạng thái kỳ thi</Link></div></section></main>
}

export function LecturerSubjectListPage() {
  const [params, setParams] = useSearchParams(); const query = params.get('q') ?? ''; const subjects = useLecturerSubjects(); const filtered = useMemo(() => (subjects.data ?? []).filter((subject) => courseLabel(subject).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [subjects.data, query])
  if (subjects.isLoading) return <LoadingPage label="Đang tải môn học" />
  if (subjects.isError) return <section className="state"><Alert tone="danger">Không thể tải danh sách môn học.</Alert><Button onClick={() => subjects.refetch()}>Thử lại</Button></section>
  return <main className="lecturer-page"><header className="lecturer-header"><div><p className="lecturer-eyebrow">LECTURER · SUBJECTS</p><h1>Môn học phụ trách</h1><p>Danh sách học phần và các tác vụ được cấp quyền.</p></div></header><section className="dashboard-section"><div className="subject-search"><label htmlFor="subject-search">Tìm theo mã hoặc tên môn học<Input id="subject-search" value={query} onChange={(event) => { const next = new URLSearchParams(params); if (event.target.value) next.set('q', event.target.value); else next.delete('q'); setParams(next) }} placeholder="Ví dụ: INT2204 hoặc Java" /></label><Button variant="outline" disabled={!query} onClick={() => setParams({})}>Xóa tìm kiếm</Button></div></section>{!subjects.data?.length ? <EmptyState title="Chưa có học phần được phân công" description="Bạn chưa có môn học nào trong danh sách phụ trách." /> : !filtered.length ? <EmptyState title="Không tìm thấy môn học" description="Thử lại với mã hoặc tên khác." /> : <div className="subject-grid">{filtered.map((subject) => <SubjectCard key={subject.id} subject={subject} />)}</div>}</main>
}

function FeatureLink({ id, label, to }: { id: string; label: string; to: string }) { const enabled = canOpenFeature(id); return enabled ? <Link className="button outline" to={to}>{label}</Link> : <span className="button outline" aria-disabled="true">{label} · Sắp có</span> }
export function LecturerSubjectOverviewPage() {
  const { courseId = '' } = useParams(); const { session } = useSession(); const subject = useLecturerSubject(courseId)
  if (session.user && !session.user.roles.includes('lecturer')) return <PermissionDenied />
  if (subject.isLoading) return <LoadingPage label="Đang tải tổng quan môn học" />
  if (subject.isError) return <ErrorState description="Không thể tải tổng quan môn học." />
  if (!subject.data) return <section className="state"><h1>Không tìm thấy môn học</h1><p>Học phần này không nằm trong danh sách được phân công.</p><Link className="button outline" to="/lecturer/subjects">Về danh sách môn học</Link></section>
  const item = subject.data; const base = `/lecturer/subjects/${item.id}`
  return <main className="lecturer-page"><nav className="muted" aria-label="Breadcrumb"><Link to="/lecturer/subjects">Môn học</Link> / <span>{item.code}</span></nav><header className="lecturer-header"><div><p className="lecturer-eyebrow">SUBJECT · OVERVIEW</p><h1>{item.name}</h1><p>{item.code} · {item.department}</p></div><div className="subject-actions"><StatusBadge label={item.status === 'ACTIVE' ? 'Đang phụ trách' : 'Đã lưu trữ'} tone={item.status === 'ACTIVE' ? 'success' : 'neutral'} /></div></header><div className="overview-layout"><section className="dashboard-section"><h2>Chỉ số học phần</h2><div className="overview-cards"><div className="overview-card"><span>Câu hỏi</span><strong>{item.questionCount ?? '—'}</strong></div><div className="overview-card"><span>Bản nháp</span><strong>{item.draftQuestionCount ?? '—'}</strong></div><div className="overview-card"><span>Đã duyệt</span><strong>{item.approvedQuestionCount ?? '—'}</strong></div><div className="overview-card"><span>Rubric</span><strong>{item.rubricCount ?? '—'}</strong></div><div className="overview-card"><span>Học liệu</span><strong>{item.materialCount ?? '—'}</strong></div><div className="overview-card"><span>Kỳ thi</span><strong>{item.examCount ?? '—'}</strong></div></div></section><section className="dashboard-section"><h2>Tác vụ học phần</h2><div className="subject-actions"><FeatureLink id={item.id} label="Ngân hàng câu hỏi" to={`${base}/questions`} /><FeatureLink id={item.id} label="Tạo câu hỏi" to={`${base}/questions/new`} /><FeatureLink id={item.id} label="Rubric chấm điểm" to={`${base}/rubrics`} /><FeatureLink id={item.id} label="Tài liệu môn học" to={`${base}/materials`} /><FeatureLink id={item.id} label="Sinh câu hỏi bằng AI" to={`${base}/questions/generate`} /></div></section></div><section className="dashboard-section"><h2>Kỳ thi</h2><p className="muted">Quản lý kỳ thi và theo dõi tiến độ.</p><div className="subject-actions"><Link className="button outline" to={examRoutes.list}>Xem kỳ thi</Link><Link className="button primary" to={examRoutes.new}>Tạo kỳ thi</Link></div></section></main>
}
