import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { questionRepository } from './question-repository'
import type { ImportedQuestionDraft } from './question-types'
import { runtimeConfig } from '../../services/api/runtime-config'
import { apiQuestionRepository, type QuestionSearchParams } from './api-question-repository'

export const questionKeys = { all: ['question-bank'] as const, list: (subjectId: string) => [...questionKeys.all, subjectId] as const, detail: (subjectId: string, questionId: string) => [...questionKeys.list(subjectId), questionId] as const }
export const apiQuestionKeys = { all: [...questionKeys.all, 'api'] as const, list: (params: QuestionSearchParams) => [...apiQuestionKeys.all, params] as const, detail: (subjectId: string, questionId: string) => [...apiQuestionKeys.all, subjectId, questionId] as const }
export function useQuestions(subjectId: string) { return useQuery({ queryKey: questionKeys.list(subjectId), queryFn: () => questionRepository.list(subjectId), enabled: Boolean(subjectId) }) }
export function useQuestion(subjectId: string, questionId: string | undefined) { return useQuery({ queryKey: questionKeys.detail(subjectId, questionId ?? ''), queryFn: () => questionRepository.get(subjectId, questionId ?? ''), enabled: Boolean(subjectId && questionId) }) }
export function useQuestionTopics(subjectId: string) { return useQuery({ queryKey: [...questionKeys.list(subjectId), 'topics'], queryFn: () => questionRepository.topics(subjectId), enabled: Boolean(subjectId) }) }
export function useImportQuestions() { const client = useQueryClient(); return useMutation({ mutationFn: ({ subjectId, drafts }: { subjectId: string; drafts: ImportedQuestionDraft[] }) => questionRepository.import(subjectId, drafts), onSuccess: (_result, variables) => client.invalidateQueries({ queryKey: questionKeys.list(variables.subjectId) }) }) }
export function useSaveQuestion() { const client = useQueryClient(); return useMutation({ mutationFn: questionRepository.save, onSuccess: (question) => client.invalidateQueries({ queryKey: questionKeys.list(question.subjectId) }) }) }
export function useApiQuestions(params: QuestionSearchParams) { return useQuery({ queryKey: apiQuestionKeys.list(params), queryFn: () => apiQuestionRepository.search(params), enabled: runtimeConfig.dataSource === 'api' && Boolean(params.courseId) }) }
export function useApiQuestion(subjectId: string, questionId: string | undefined) { return useQuery({ queryKey: apiQuestionKeys.detail(subjectId, questionId ?? ''), queryFn: () => apiQuestionRepository.get(subjectId, questionId ?? ''), enabled: runtimeConfig.dataSource === 'api' && Boolean(subjectId && questionId) }) }
export function useApproveApiQuestion() { const client = useQueryClient(); return useMutation({ mutationFn: ({ subjectId, questionId }: { subjectId: string; questionId: string }) => apiQuestionRepository.approve(subjectId, questionId), onSuccess: (question, variables) => { client.setQueryData(apiQuestionKeys.detail(variables.subjectId, variables.questionId), question); client.invalidateQueries({ queryKey: apiQuestionKeys.all }) } }) }
export function useDeleteApiQuestion() { const client = useQueryClient(); return useMutation({ mutationFn: ({ subjectId, questionId }: { subjectId: string; questionId: string }) => apiQuestionRepository.delete(subjectId, questionId), onSuccess: (_result, variables) => { client.removeQueries({ queryKey: apiQuestionKeys.detail(variables.subjectId, variables.questionId) }); client.invalidateQueries({ queryKey: apiQuestionKeys.all }) } }) }
