import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { examRepository } from './exam-repository'
import type { ExamDraft, ExamListRequest } from './exam-types'
import type { RosterDraft } from './roster-types'
import type { ScheduleDraft } from './schedule-types'
import type { QuestionConfigDraft } from './question-config-types'
import { apiExamSchedulingRepository, type AutoScheduleRequestDto, type RescheduleCandidateRequestDto } from './api-exam-scheduling-repository'
import { apiExamMonitoringRepository } from './api-exam-monitoring-repository'
import { apiStudentExamRepository } from './api-student-exam-repository'
import { useSession } from '../../app/providers/use-session'
import { runtimeConfig } from '../../services/api/runtime-config'
import { subjectRepository } from '../subjects/subject-repository'

export const examKeys = { all: ['exams'] as const, lists: ['exams', 'list'] as const, list: (request: ExamListRequest) => [...examKeys.lists, request] as const, detail: (examId: string) => [...examKeys.all, 'detail', examId] as const, roster: (examId: string) => [...examKeys.all, 'roster', examId] as const, schedule: (examId: string) => [...examKeys.all, 'schedule', examId] as const, questionConfig: (examId: string) => [...examKeys.all, 'question-config', examId] as const, subjects: (lecturerId: string) => [...examKeys.all, 'subjects', lecturerId] as const, summary: () => [...examKeys.all, 'summary'] as const }
export function useExams(request: ExamListRequest) { return useQuery({ queryKey: examKeys.list(request), queryFn: () => examRepository.list(request) }) }
export function useExam(examId: string | undefined) { return useQuery({ queryKey: examKeys.detail(examId ?? ''), queryFn: () => examRepository.get(examId ?? ''), enabled: Boolean(examId) }) }
export function useExamSubjects() {
  const { session } = useSession()
  const lecturerId = session.user?.id ?? ''
  return useQuery({ queryKey: examKeys.subjects(lecturerId), queryFn: async () => runtimeConfig.dataSource === 'api' ? (await subjectRepository.list(lecturerId)).map((subject) => ({ id: subject.id, code: subject.code, name: subject.name })) : examRepository.subjects(), enabled: Boolean(session.user), staleTime: Infinity })
}
export function useExamSummary() { return useQuery({ queryKey: examKeys.summary(), queryFn: () => examRepository.summary(), staleTime: Infinity }) }
export function useExamRoster(examId: string | undefined) { return useQuery({ queryKey: examKeys.roster(examId ?? ''), queryFn: () => examRepository.listRoster(examId ?? ''), enabled: Boolean(examId) }) }
export function useExamSchedule(examId: string | undefined) { return useQuery({ queryKey: examKeys.schedule(examId ?? ''), queryFn: async () => (await examRepository.getSchedule(examId ?? '')) ?? null, enabled: Boolean(examId) }) }
export function useExamQuestionConfig(examId: string | undefined) { return useQuery({ queryKey: examKeys.questionConfig(examId ?? ''), queryFn: async () => (await examRepository.getQuestionConfig(examId ?? '')) ?? null, enabled: Boolean(examId) }) }
function invalidateRoster(client: ReturnType<typeof useQueryClient>, examId: string) { client.invalidateQueries({ queryKey: examKeys.roster(examId) }); client.invalidateQueries({ queryKey: examKeys.detail(examId) }); client.invalidateQueries({ queryKey: examKeys.lists }) }
export function useAddRosterStudent() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, draft }: { examId: string; draft: RosterDraft }) => examRepository.addRosterStudent(examId, draft), onSuccess: (_, variables) => invalidateRoster(client, variables.examId) }) }
export function useImportRosterStudents() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, drafts }: { examId: string; drafts: RosterDraft[] }) => examRepository.importRosterStudents(examId, drafts), onSuccess: (_, variables) => invalidateRoster(client, variables.examId) }) }
export function useRemoveRosterStudent() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, rosterId }: { examId: string; rosterId: string }) => examRepository.removeRosterStudent(examId, rosterId), onSuccess: (_, variables) => invalidateRoster(client, variables.examId) }) }
export function useSaveExamSchedule() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, draft }: { examId: string; draft: ScheduleDraft }) => examRepository.saveSchedule(examId, draft), onSuccess: (schedule, variables) => { client.setQueryData(examKeys.schedule(variables.examId), schedule); client.invalidateQueries({ queryKey: examKeys.detail(variables.examId) }) } }) }
export function useSaveExamQuestionConfig() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, draft }: { examId: string; draft: QuestionConfigDraft }) => examRepository.saveQuestionConfig(examId, draft), onSuccess: (config, variables) => { client.setQueryData(examKeys.questionConfig(variables.examId), config); client.invalidateQueries({ queryKey: examKeys.detail(variables.examId) }) } }) }
export const apiExamKeys = { all: ['api-exams'] as const, schedule: (examId: string) => [...apiExamKeys.all, 'schedule', examId] as const }
export function useApiExamSchedule(examId: string | undefined) { return useQuery({ queryKey: apiExamKeys.schedule(examId ?? ''), queryFn: () => apiExamSchedulingRepository.getSchedule(examId ?? ''), enabled: Boolean(examId) }) }
function invalidateApiExam(client: ReturnType<typeof useQueryClient>, examId: string) { client.invalidateQueries({ queryKey: apiExamKeys.schedule(examId) }); client.invalidateQueries({ queryKey: examKeys.detail(examId) }); client.invalidateQueries({ queryKey: examKeys.lists }) }
export function useAssignApiCandidates() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, studentIds }: { examId: string; studentIds: string[] }) => apiExamSchedulingRepository.assignCandidates(examId, studentIds), onSuccess: (_, variables) => invalidateApiExam(client, variables.examId) }) }
export function useAutoScheduleApiExam() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, request }: { examId: string; request: AutoScheduleRequestDto }) => apiExamSchedulingRepository.autoSchedule(examId, request), onSuccess: (schedule, variables) => { client.setQueryData(apiExamKeys.schedule(variables.examId), schedule); invalidateApiExam(client, variables.examId) } }) }
export function useRescheduleApiExam() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, request }: { examId: string; request: RescheduleCandidateRequestDto }) => apiExamSchedulingRepository.reschedule(examId, request), onSuccess: (_, variables) => invalidateApiExam(client, variables.examId) }) }
export function useCreateExam() { const client = useQueryClient(); return useMutation({ mutationFn: (draft: ExamDraft) => examRepository.create(draft), onSuccess: (exam) => { client.invalidateQueries({ queryKey: examKeys.lists }); client.invalidateQueries({ queryKey: examKeys.summary() }); client.setQueryData(examKeys.detail(exam.id), exam) } }) }
export function useUpdateExam() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, draft }: { examId: string; draft: ExamDraft }) => examRepository.update(examId, draft), onSuccess: (exam) => { client.setQueryData(examKeys.detail(exam.id), exam); client.invalidateQueries({ queryKey: examKeys.lists }); client.invalidateQueries({ queryKey: examKeys.summary() }) } }) }
export function useDeleteExam() { const client = useQueryClient(); return useMutation({ mutationFn: (examId: string) => examRepository.delete(examId), onSuccess: (_, examId) => { client.removeQueries({ queryKey: examKeys.detail(examId) }); client.removeQueries({ queryKey: examKeys.schedule(examId) }); client.removeQueries({ queryKey: examKeys.roster(examId) }); client.invalidateQueries({ queryKey: examKeys.lists }); client.invalidateQueries({ queryKey: examKeys.summary() }); client.invalidateQueries({ queryKey: apiExamKeys.schedule(examId) }) } }) }
export function useUpdateExamStatus() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, status }: { examId: string; status: import('./exam-types').ExamStatus }) => examRepository.updateStatus(examId, status), onSuccess: (exam) => { client.setQueryData(examKeys.detail(exam.id), exam); client.invalidateQueries({ queryKey: examKeys.lists }); client.invalidateQueries({ queryKey: examKeys.summary() }); client.invalidateQueries({ queryKey: examKeys.schedule(exam.id) }); client.invalidateQueries({ queryKey: apiExamKeys.schedule(exam.id) }) } }) }
export const monitoringKeys = { all: ['exam-monitoring'] as const, detail: (examId: string) => [...monitoringKeys.all, examId] as const }
export function useExamMonitoring(examId: string | undefined) { return useQuery({ queryKey: monitoringKeys.detail(examId ?? ''), queryFn: () => apiExamMonitoringRepository.get(examId ?? ''), enabled: Boolean(examId) }) }
function invalidateMonitoring(client: ReturnType<typeof useQueryClient>, examId: string) { client.invalidateQueries({ queryKey: monitoringKeys.detail(examId) }); client.invalidateQueries({ queryKey: apiExamKeys.schedule(examId) }); client.invalidateQueries({ queryKey: examKeys.detail(examId) }) }
export function useResetExamAttempt() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, attemptId }: { examId: string; attemptId: string }) => apiExamMonitoringRepository.reset(examId, attemptId), onSuccess: (_, variables) => invalidateMonitoring(client, variables.examId) }) }
export function useMarkExamAttemptAbsent() { const client = useQueryClient(); return useMutation({ mutationFn: ({ examId, attemptId }: { examId: string; attemptId: string }) => apiExamMonitoringRepository.absent(examId, attemptId), onSuccess: (_, variables) => invalidateMonitoring(client, variables.examId) }) }
export const studentExamKeys = { all: ['student-exams'] as const, slot: (examId: string, studentId: string) => [...studentExamKeys.all, examId, studentId] as const }
export function useStudentMySlot(examId: string | undefined, studentId: string | undefined) { return useQuery({ queryKey: studentExamKeys.slot(examId ?? '', studentId ?? ''), queryFn: () => apiStudentExamRepository.getMySlot(examId ?? '', studentId ?? ''), enabled: Boolean(examId && studentId) }) }
