import { useMemo, useRef, useState, type FormEvent } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { Alert, Button, Dialog, Input, Spinner } from '../../components/ui/primitives'
import { EmptyState, ErrorState, LoadingPage, PermissionDenied, StatusBadge } from '../../components/common/states'
import { useSession } from '../../app/providers/use-session'
import { useAddRosterStudent, useExam, useExamRoster, useImportRosterStudents, useRemoveRosterStudent } from './exam-hooks'
import { examStatusMeta } from './exam-types'
import { parseRosterFile, rosterImportTemplateUrl } from './roster-import-parser'
import { normalizeRosterDraft, validateRosterDraft } from './roster-validation'
import type { RosterDraft, RosterImportPreview, RosterStudent } from './roster-types'
import './exam-student-roster.css'

export function ExamStudentRosterPage() {
  const { examId = '' } = useParams(); const { session } = useSession(); const [params, setParams] = useSearchParams(); const [addOpen, setAddOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [remove, setRemove] = useState<RosterStudent | null>(null)
  const exam = useExam(examId); const roster = useExamRoster(examId); const editable = exam.data ? exam.data.status === 'DRAFT' || exam.data.status === 'SCHEDULED' : false; const query = (params.get('q') ?? '').trim().toLocaleLowerCase(); const rows = useMemo(() => (roster.data ?? []).filter((student) => `${student.studentCode} ${student.fullName} ${student.email}`.toLocaleLowerCase().includes(query)), [roster.data, query])
  if (session.user && !session.user.roles.includes('lecturer')) return <PermissionDenied />
  if (exam.isLoading) return <LoadingPage label="Đang tải kỳ thi" />
  if (exam.isError) return <ErrorState description="Không thể tải thông tin kỳ thi. Vui lòng thử lại." />
  if (!exam.data) return <ErrorState description="Không tìm thấy kỳ thi." />
  const meta = examStatusMeta[exam.data.status]
  return <section className="roster-page"><header className="roster-head"><div><p className="eyebrow">EXAMS · STUDENT ROSTER</p><div className="roster-breadcrumb"><Link to="/lecturer/exams">Kỳ thi</Link><span>/</span><span>{exam.data.id}</span></div><h1>Danh sách sinh viên</h1><p>{exam.data.title} · {exam.data.subjectName}</p></div><div className="roster-head-actions"><StatusBadge label={meta.label} tone={meta.tone} /><Link className="button outline" to={`/lecturer/exams/${examId}`}>Quay lại kỳ thi</Link></div></header>
    {!editable && <Alert tone="warning"><strong>Chế độ chỉ đọc.</strong> Kỳ thi {meta.label.toLocaleLowerCase()} nên không thể thêm, import hoặc xoá sinh viên.</Alert>}
    {editable && <div className="roster-toolbar"><Button onClick={() => setAddOpen(true)}>Thêm sinh viên</Button><Button variant="outline" onClick={() => setImportOpen(true)}>Import CSV</Button><a className="button outline" download="aives-exam-student-roster-template.csv" href={rosterImportTemplateUrl}>Tải file mẫu</a></div>}
    <div className="roster-filters"><label htmlFor="roster-search">Tìm sinh viên<Input id="roster-search" value={params.get('q') ?? ''} onChange={(event) => { const next = new URLSearchParams(params); if (event.target.value) next.set('q', event.target.value); else next.delete('q'); setParams(next) }} placeholder="Mã sinh viên, họ tên hoặc email..." /></label><span>{roster.data?.length ?? 0} sinh viên</span></div>
    {roster.isLoading ? <LoadingPage label="Đang tải danh sách sinh viên" /> : roster.isError ? <section className="state"><Alert tone="danger">Không thể tải danh sách sinh viên.</Alert><Button onClick={() => roster.refetch()}>Thử lại</Button></section> : !roster.data?.length ? <EmptyState title="Chưa có sinh viên" description="Thêm thủ công hoặc import danh sách CSV để bắt đầu." /> : !rows.length ? <section className="state"><h2>Không tìm thấy sinh viên</h2><p>Thử tìm theo mã, họ tên hoặc email khác.</p><Button variant="outline" onClick={() => setParams({})}>Xóa tìm kiếm</Button></section> : <div className="roster-table-wrap"><table className="roster-table"><caption className="sr-only">Danh sách sinh viên của {exam.data.title}</caption><thead><tr><th>MÃ SINH VIÊN</th><th>HỌ VÀ TÊN</th><th>EMAIL</th><th>THAO TÁC</th></tr></thead><tbody>{rows.map((student) => <tr key={student.id}><td>{student.studentCode}</td><td>{student.fullName}</td><td>{student.email}</td><td>{editable && <Button variant="danger" onClick={() => setRemove(student)}>Xoá</Button>}</td></tr>)}</tbody></table></div>}
    <AddStudentDialog open={addOpen} examId={examId} existing={roster.data ?? []} onClose={() => setAddOpen(false)} />
    <ImportRosterDialog open={importOpen} examId={examId} existing={roster.data ?? []} onClose={() => setImportOpen(false)} />
    <RemoveStudentDialog student={remove} examId={examId} onClose={() => setRemove(null)} />
  </section>
}

function AddStudentDialog({ open, examId, existing, onClose }: { open: boolean; examId: string; existing: RosterStudent[]; onClose: () => void }) { const mutation = useAddRosterStudent(); const [draft, setDraft] = useState<RosterDraft>({ studentCode: '', fullName: '', email: '' }); const [issues, setIssues] = useState<string[]>([]); const submit = (event: FormEvent) => { event.preventDefault(); const value = normalizeRosterDraft(draft); const next = validateRosterDraft(value, existing); setIssues(next.map((issue) => issue.message)); if (next.length) return; mutation.mutate({ examId, draft: value }, { onSuccess: () => { setDraft({ studentCode: '', fullName: '', email: '' }); setIssues([]); onClose() } }) }; return <Dialog open={open} onClose={onClose} title="Thêm sinh viên"><form className="roster-form" onSubmit={submit}><label>Mã sinh viên<Input value={draft.studentCode} onChange={(e) => setDraft({ ...draft, studentCode: e.target.value })} /></label><label>Họ và tên<Input value={draft.fullName} onChange={(e) => setDraft({ ...draft, fullName: e.target.value })} /></label><label>Email<Input type="email" value={draft.email} onChange={(e) => setDraft({ ...draft, email: e.target.value })} /></label>{issues.map((issue) => <Alert key={issue} tone="danger">{issue}</Alert>)}{mutation.isError && <Alert tone="danger">Không thể thêm sinh viên. Dữ liệu đã nhập được giữ lại.</Alert>}<div className="dialog-actions"><Button type="button" variant="outline" onClick={onClose}>Huỷ</Button><Button type="submit" pending={mutation.isPending}>Thêm sinh viên</Button></div></form></Dialog> }

function ImportRosterDialog({ open, examId, existing, onClose }: { open: boolean; examId: string; existing: RosterStudent[]; onClose: () => void }) { const inputRef = useRef<HTMLInputElement>(null); const mutation = useImportRosterStudents(); const [preview, setPreview] = useState<RosterImportPreview | null>(null); const [errors, setErrors] = useState<string[]>([]); const [parsing, setParsing] = useState(false); const process = async (file?: File) => { if (!file) return; setParsing(true); setErrors([]); try { const result = await parseRosterFile(file, existing); setPreview(result.preview); setErrors(result.fileErrors) } catch { setErrors(['Không thể đọc tệp CSV.']) } finally { setParsing(false) } }; const submit = () => { if (!preview?.valid) return; mutation.mutate({ examId, drafts: preview.rows.flatMap((row) => row.draft ? [row.draft] : []) }, { onSuccess: () => { setPreview(null); onClose() } }) }; return <Dialog open={open} onClose={onClose} title="Import danh sách CSV"><div className="import-roster-content"><p>UTF-8/BOM · tối đa 5 MB · tối đa 500 dòng dữ liệu.</p><a className="button outline" download="aives-exam-student-roster-template.csv" href={rosterImportTemplateUrl}>Tải file mẫu CSV</a><label className="roster-dropzone" htmlFor="roster-file"><strong>Chọn tệp CSV</strong><span>Headers: student_code, full_name, email</span></label><input ref={inputRef} id="roster-file" className="import-file-input" type="file" accept=".csv,text/csv" onChange={(e) => void process(e.target.files?.[0])} />{parsing && <p><Spinner label="Đang phân tích CSV" /> Đang phân tích…</p>}{errors.map((error) => <Alert key={error} tone="danger">{error}</Alert>)}{preview && <div className="roster-preview" aria-live="polite"><div className="import-summary"><span>Tổng <strong>{preview.total}</strong></span><span>Hợp lệ <strong>{preview.valid}</strong></span><span>Lỗi <strong>{preview.invalid}</strong></span></div><div className="roster-preview-table"><table><thead><tr><th>Dòng</th><th>Mã</th><th>Họ tên</th><th>Trạng thái</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.id}><td>{row.rowNumber}</td><td>{row.raw.student_code}</td><td>{row.raw.full_name}</td><td>{row.issues.length ? <><StatusBadge label="Lỗi" tone="danger" /><ul>{row.issues.map((issue) => <li key={`${issue.column}-${issue.message}`}>{issue.message}</li>)}</ul></> : <StatusBadge label="Hợp lệ" tone="success" />}</td></tr>)}</tbody></table></div>{!preview.valid && <Alert tone="danger">Không có dòng hợp lệ để import.</Alert>}</div>}{mutation.isError && <Alert tone="danger">Import thất bại. Hãy kiểm tra lại dữ liệu và thử lại.</Alert>}<div className="dialog-actions"><Button variant="outline" onClick={onClose}>Huỷ</Button><Button disabled={!preview?.valid || parsing} pending={mutation.isPending} onClick={submit}>Import {preview?.valid ?? 0} dòng</Button></div></div></Dialog> }

function RemoveStudentDialog({ student, examId, onClose }: { student: RosterStudent | null; examId: string; onClose: () => void }) { const mutation = useRemoveRosterStudent(); return <Dialog open={Boolean(student)} onClose={onClose} title="Xoá sinh viên khỏi kỳ thi"><p>Xác nhận xoá <strong>{student?.fullName}</strong> ({student?.studentCode}) khỏi danh sách kỳ thi này?</p>{mutation.isError && <Alert tone="danger">Không thể xoá sinh viên. Danh sách được giữ nguyên.</Alert>}<div className="dialog-actions"><Button variant="outline" onClick={onClose}>Huỷ</Button><Button variant="danger" pending={mutation.isPending} onClick={() => student && mutation.mutate({ examId, rosterId: student.id }, { onSuccess: onClose })}>Xác nhận xoá</Button></div></Dialog> }
