import { describe, expect, it, vi } from 'vitest'
import { ApiError, apiClient, buildApiUrl } from './client'
import { normalizeApiPage, normalizeSpringPage, unwrapApiEnvelope } from './transport-types'
import { DEFAULT_API_TIMEOUT_MS, normalizeApiBaseUrl, parseRuntimeConfig } from './runtime-config'
import { selectRepository } from './repository-selection'

describe('runtime configuration', () => {
  it('defaults to mock mode and the documented timeout', () => { expect(parseRuntimeConfig({})).toEqual({ apiBaseUrl: '', apiTimeoutMs: DEFAULT_API_TIMEOUT_MS, dataSource: 'mock', demoCourseId: '', demoExamId: '', demoCandidateIds: [] }) })
  it('parses api mode, valid timeout and demo IDs', () => { expect(parseRuntimeConfig({ VITE_DATA_SOURCE: 'api', VITE_API_BASE_URL: 'https://api.example.test///', VITE_API_TIMEOUT_MS: '3000', VITE_DEMO_COURSE_ID: ' course-1 ', VITE_DEMO_EXAM_ID: 'exam-1', VITE_DEMO_CANDIDATE_IDS: 'student-1, student-2' })).toEqual({ apiBaseUrl: 'https://api.example.test', apiTimeoutMs: 3000, dataSource: 'api', demoCourseId: 'course-1', demoExamId: 'exam-1', demoCandidateIds: ['student-1', 'student-2'] }) })
  it('falls back safely for invalid mode and timeout', () => { expect(parseRuntimeConfig({ VITE_DATA_SOURCE: 'remote', VITE_API_TIMEOUT_MS: '-1' })).toMatchObject({ dataSource: 'mock', apiTimeoutMs: DEFAULT_API_TIMEOUT_MS }) })
  it('normalizes empty and trailing-slash base URLs', () => { expect(normalizeApiBaseUrl(undefined)).toBe(''); expect(normalizeApiBaseUrl(' https://api.test/// ')).toBe('https://api.test') })
})

describe('URL and repository boundaries', () => {
  it('joins paths and encodes queries while preserving false and zero', () => { expect(buildApiUrl('https://api.test/', '/api/questions', { page: 0, active: false, keyword: 'OOP & Java', empty: null, missing: undefined })).toBe('https://api.test/api/questions?page=0&active=false&keyword=OOP+%26+Java') })
  it('supports repeated query values and rejects absolute endpoint paths', () => { expect(buildApiUrl('', '/api/questions', { status: ['DRAFT', 'APPROVED'] })).toBe('/api/questions?status=DRAFT&status=APPROVED'); expect(() => buildApiUrl('', 'https://evil.test')).toThrow(ApiError) })
  it('selects only the configured repository without fallback', () => { const mock = { source: 'mock' }; const api = { source: 'api' }; expect(selectRepository('mock', { mock, api })).toBe(mock); expect(selectRepository('api', { mock, api })).toBe(api) })
})

describe('API client', () => {
  it('handles GET JSON and arrays', async () => { vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(new Response('{"ok":true}', { status: 200 })).mockResolvedValueOnce(new Response('[1,2]', { status: 200 }))); await expect(apiClient.request<{ ok: boolean }>('/api/test')).resolves.toEqual({ ok: true }); await expect(apiClient.request<number[]>('/api/list')).resolves.toEqual([1, 2]) })
  it.each(['POST', 'PUT', 'PATCH'] as const)('sends %s JSON bodies', async (method) => { const fetchMock = vi.fn().mockResolvedValue(new Response('{"saved":true}', { status: 200 })); vi.stubGlobal('fetch', fetchMock); await apiClient.request('/api/test', { method, body: { name: 'safe' }, headers: { 'X-Request-ID': '1' } }); const init = fetchMock.mock.calls[0][1] as RequestInit; expect(init.method).toBe(method); expect(init.body).toBe('{"name":"safe"}'); expect(new Headers(init.headers).get('content-type')).toBe('application/json'); expect(new Headers(init.headers).get('x-request-id')).toBe('1') })
  it('handles DELETE 204 and successful empty bodies', async () => { vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(new Response(null, { status: 204 })).mockResolvedValueOnce(new Response('', { status: 200 }))); await expect(apiClient.request('/api/test', { method: 'DELETE' })).resolves.toBeUndefined(); await expect(apiClient.request('/api/empty')).resolves.toBeUndefined() })
  it('normalizes backend errors and field validation', async () => { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response(JSON.stringify({ success: false, status: 400, message: 'Dữ liệu sai', data: { email: 'Email không hợp lệ' } }), { status: 400, headers: { 'Content-Type': 'application/json' } }))); const error = await apiClient.request('/api/test').catch((value: unknown) => value as ApiError); expect(error).toMatchObject({ status: 400, message: 'Dữ liệu sai', fieldErrors: { email: 'Email không hợp lệ' } }) })
  it.each([404, 409, 500])('preserves HTTP status %s', async (status) => { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('', { status }))); await expect(apiClient.request('/api/test')).rejects.toMatchObject({ status }) })
  it('normalizes network, timeout and caller cancellation', async () => { vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new Error('offline'))); await expect(apiClient.request('/api/test')).rejects.toMatchObject({ code: 'NETWORK_ERROR' }); vi.useFakeTimers(); const timeoutFetch = vi.fn((_input: RequestInfo | URL, init?: RequestInit) => new Promise<Response>((_, reject) => init?.signal?.addEventListener('abort', () => reject(new DOMException('aborted', 'AbortError')), { once: true }))); vi.stubGlobal('fetch', timeoutFetch); const timeout = apiClient.request('/api/test', { timeoutMs: 10 }); const timeoutExpectation = expect(timeout).rejects.toMatchObject({ code: 'TIMEOUT' }); await vi.advanceTimersByTimeAsync(10); await timeoutExpectation; vi.useRealTimers(); const controller = new AbortController(); const abortFetch = vi.fn((_input: RequestInfo | URL, init?: RequestInit) => new Promise<Response>((_, reject) => init?.signal?.addEventListener('abort', () => reject(new DOMException('aborted', 'AbortError')), { once: true }))); vi.stubGlobal('fetch', abortFetch); const aborted = apiClient.request('/api/test', { signal: controller.signal }); controller.abort(); await expect(aborted).rejects.toMatchObject({ code: 'ABORTED' }) })
  it('rejects malformed success and error JSON without exposing HTML', async () => { vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(new Response('not-json', { status: 200 })).mockResolvedValueOnce(new Response('<html>proxy error</html>', { status: 502 }))); await expect(apiClient.request('/api/test')).rejects.toMatchObject({ code: 'INVALID_RESPONSE' }); await expect(apiClient.request('/api/test')).rejects.toMatchObject({ status: 502, message: 'Yêu cầu thất bại (502).' }) })
})

describe('transport helpers', () => {
  it('unwraps envelopes explicitly', () => { expect(unwrapApiEnvelope({ success: true, status: 200, message: 'ok', data: { id: 1 } })).toEqual({ id: 1 }); expect(() => unwrapApiEnvelope({ success: false, status: 400, message: 'bad', data: { name: 'invalid' } })).toThrow('bad') })
  it('normalizes Spring and Admin page shapes', () => { expect(normalizeSpringPage({ content: ['a'], number: 1, size: 10, totalElements: 11, totalPages: 2 })).toEqual({ items: ['a'], page: 1, pageSize: 10, totalItems: 11, totalPages: 2 }); expect(normalizeApiPage({ content: ['b'], page: 0, size: 20, totalElements: 1, totalPages: 1 })).toEqual({ items: ['b'], page: 0, pageSize: 20, totalItems: 1, totalPages: 1 }) })
})
