#!/usr/bin/env bash
set -euo pipefail

echo "Creating AIVES agent-first frontend structure..."

dirs=(
  ".agent/plans/active"
  ".agent/plans/completed"
  ".agent/tasks"
  ".agent/roles"
  ".agent/prompts"
  ".agent/checklists"
  ".agent/state"
  "docs/product"
  "docs/design"
  "docs/architecture"
  "docs/api"
  "docs/quality"
  "raw/stitch/screenshots"
  "raw/stitch/prototype"
  "raw/stitch/exported-code"
  "raw/stitch/notes"
  "src/app/router"
  "src/app/providers"
  "src/app/layouts"
  "src/app/guards"
  "src/pages"
  "src/features/auth"
  "src/features/dashboard"
  "src/features/subjects"
  "src/features/learning-materials"
  "src/features/question-bank"
  "src/features/rubrics"
  "src/features/exams"
  "src/features/viva-session"
  "src/features/grading"
  "src/features/monitoring"
  "src/features/reports"
  "src/features/students"
  "src/features/administration"
  "src/components/ui"
  "src/components/common"
  "src/services/api"
  "src/services/realtime"
  "src/services/media"
  "src/hooks"
  "src/store"
  "src/lib"
  "src/types"
  "src/constants"
  "src/styles"
  "tests/unit"
  "tests/integration"
  "tests/e2e"
  "scripts"
)

for dir in "${dirs[@]}"; do
  mkdir -p "$dir"
  touch "$dir/.gitkeep"
done

echo "Done."
