import { useEffect, useId, useRef, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode } from 'react'
export function Button({ variant = 'primary', pending, className = '', children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'outline' | 'danger'; pending?: boolean }) { return <button className={`button ${variant} ${className}`} disabled={props.disabled || pending} {...props}>{pending ? 'Đang xử lý…' : children}</button> }
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input className="input" {...props} /> }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'info' | 'success' | 'warning' | 'danger' | 'ai' }) { return <span className={`badge ${tone}`}>{children}</span> }
export function Alert({ children, tone = 'info' }: { children: ReactNode; tone?: 'info' | 'success' | 'warning' | 'danger' }) { return <div className={`alert ${tone}`} role="status">{children}</div> }
export function Skeleton({ label = 'Đang tải' }: { label?: string }) { return <span aria-label={label} className="skeleton" role="status" /> }
export function Spinner({ label = 'Đang tải' }: { label?: string }) { return <span aria-label={label} className="spinner" role="status" /> }
export function Progress({ label, value, max = 100 }: { label: string; value: number; max?: number }) { return <label className="progress">{label}<progress max={max} value={value} /></label> }
export function Dialog({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: ReactNode }) { const ref = useRef<HTMLDialogElement>(null); const titleId = useId(); useEffect(() => { const node = ref.current; if (!node) return; if (open && !node.open) node.showModal(); if (!open && node.open) node.close() }, [open]); return <dialog aria-labelledby={titleId} className="dialog" onCancel={(event) => { event.preventDefault(); onClose() }} ref={ref}><header><h2 id={titleId}>{title}</h2><Button aria-label="Đóng hộp thoại" onClick={onClose} variant="outline">Đóng</Button></header>{children}</dialog> }
